<?php 
$title = "LinkedIn Writer with emoji - A tool to write clean and awesome post with emojis";
$header_data = '';
include('header.php');

?>

<section class="post-writer-section">
    <div class="fluid-container space-manager">
            <h5 class="new-h1">
                Write your heart out ❤️  
            </h5>
            <div class="row">
                <div class="col-md-8">
                    <textarea class="form-control" id="post_writer" rows="10"></textarea>
                  
                </div>
                <div class="col-md-4">
                    <a onclick="clean();" href="#" >Clean everything</a>
                    <div class="common-emoji-list" id="common_emoji_list">
                    </div>
                </div>                    
            </div>
    </div>
</section>
<section class="emoji-section">
    <div class="fluid-container space-manager">
        <div class="row">
        <div class="col-md-12">
                    <button class="btn btn-primary" id="btnClipboard" style="margin-bottom:2px;" onClick="copyToClipboard()">
                        Copy Clipboard
                    </button>

                    <a class="new-tab" onclick="onHeadEmoji();">😂 Head Emojis</a>
                    <a class="new-tab" onclick="onHandEmoji();">👍 Hand Emojis</a>
                    <a class="new-tab" onclick="onSparkle();">🔥 Sparkle</a>
                    <a class="new-tab" onclick="onManWomen();">🚶🏼 Man & Women</a>
                    <a class="new-tab" onclick="onAnimalNature();">🐶 Animal & Nature</a>
                    <a class="new-tab" onclick="onFoodDrink();">🍓 Food & Drink</a>
                    <a class="new-tab" onclick="onTravel();">🚀 Travel & Distance</a>
                    <a class="new-tab" onclick="onSymbol();">❤️ Symbol</a>
                    <div class="emoji-list" id="emoji_heads">                              
                        <span>😀</span>
                        <span>😬</span>
                        <span>😁</span>
                        <span>😂</span>
                        <span>😃</span>
                        <span>😄</span>
                        <span>😅</span>
                        <span>😆</span>
                        <span>😇</span>
                        <span>😉</span>
                        <span>😊</span>
                        <span>😋</span>
                        <span>😌</span>
                        <span>😍</span>
                        <span>😘</span>
                        <span>😗</span>
                        <span>😙</span>
                        <span>😚</span>
                        <span>😜</span>
                        <span>😝</span>
                        <span>😛</span>
                        <span>😎</span>
                        <span>😏</span>
                        <span>😶</span>
                        <span>😐</span>
                        <span>😑</span>
                        <span>😒</span>
                        <span>😳</span>
                        <span>😞</span>
                        <span>😟</span>
                        <span>😠</span>
                        <span>😡</span>
                        <span>😔</span>
                        <span>😕</span>
                        <span>😣</span>
                        <span>😖</span>
                        <span>😫</span>
                        <span>😩</span>
                        <span>😤</span>
                        <span>😮</span>
                        <span>😱</span>
                        <span>😨</span>
                        <span>😰</span>
                        <span>😯</span>
                        <span>😦</span>
                        <span>😧</span>
                        <span>😢</span>
                        <span>😥</span>
                        <span>😪</span>
                        <span>😓</span>
                        <span>😭</span>
                        <span>😵</span>
                        <span>😲</span>
                        <span>😷</span>
                        <span>😴</span>
                        <span>💤</span>
                        <span>💩</span>
                        <span>😈</span>
                        <span>👿</span>
                        <span>👹</span>
                        <span>👺</span>
                        <span>💀</span>
                        <span>👻</span>
                        <span>👽</span>
                        <span>😺</span>
                        <span>😸</span>
                        <span>😹</span>
                        <span>😻</span>
                        <span>😼</span>
                        <span>😽</span>
                        <span>🙀</span>
                        <span>😿</span>
                        <span>😾</span>
                    </div>
                    <div class="emoji-list" id="hand_emojis" style="display:none">
                        <span>🙌</span>
                        <span>👏</span>
                        <span>👋</span>
                        <span>👍</span>
                        <span>👊</span>
                        <span>✊</span>
                        <span>✌️</span>
                        <span>👌</span>
                        <span>✋</span>
                        <span>💪</span>
                        <span>🙏</span>
                        <span>☝️</span>
                        <span>👆</span>
                        <span>👇</span>
                        <span>👈</span>
                        <span>👉</span>
                        <span>🖖</span>
                        <span>💪🏻</span>
                        <span>👈🏻</span>
                        <span>👉🏻</span>
                        <span>👆🏻</span>
                        <span>👇🏻</span>
                        <span>🖖🏻</span>
                        <span>✊🏻</span>
                        <span>✋🏻</span>
                        <span>👊🏻</span>
                        <span>👌🏻</span>
                        <span>👍🏻</span>
                        <span>👎🏻</span>
                        <span>👋🏻</span>
                        <span>👏🏻</span>
                        <span>👐🏻</span>
                        <span>💪🏿</span>
                        <span>👈🏿</span>
                        <span>👉🏿</span>
                        <span>👆🏿</span>
                        <span>👇🏿</span>
                        <span>🖖🏾</span>
                        <span>✊🏾</span>
                        <span>✋🏾</span>
                        <span>👊🏾</span>
                        <span>👌🏾</span>
                        <span>👍🏾</span>
                        <span>👎🏾</span>
                        <span>👋🏾</span>
                        <span>👏🏾</span>
                        <span>👐🏾</span>
                    </div>
                    <div class="emoji-list" id="emoji_sparkle" style="display:none">
                        <span>🔥</span>
                        <span>✨</span>
                        <span>🌱</span>
                        <span>🏝️</span>
                        <span>🐣</span>
                        <span>🌞</span>
                        <span>🌈</span>
                        <span>🌻</span>
                    </div>
                    <div class="emoji-list" id="emoji_man_women" style="display:none"> 
                        <span>🚶🏼</span>
                        <span>🏃🏼</span>
                        <span>💃🏼</span>
                        <span>🚣🏼</span>
                        <span>🛀🏼</span>
                        <span>🏄🏼</span>
                        <span>🏇🏼</span>
                        <span>🏊🏼</span>
                        <span>🚴🏼</span>
                        <span>🚵🏼</span>
                        <span>💆🏼</span>
                        <span>💇🏼</span>
                        <span>👰🏼</span>
                        <span>🙍🏼</span>
                        <span>🙎🏼</span>
                        <span>🙅🏼</span>
                        <span>🙆🏼</span>
                        <span>💁🏼</span>
                        <span>🙋🏼</span>
                        <span>🙇🏼</span>
                        <span>🚶🏽</span>
                        <span>🏃🏽</span>
                        <span>💃🏽</span>
                        <span>🚣🏽</span>
                        <span>🛀🏽</span>
                        <span>🏄🏽</span>
                        <span>🏇🏽</span>
                        <span>🏊🏽</span>
                        <span>🚴🏽</span>
                        <span>🚵🏽</span>
                        <span>💆🏽</span>
                        <span>💇🏽</span>
                        <span>👰🏽</span>
                        <span>🙍🏽</span>
                        <span>🙎🏽</span>
                        <span>🙅🏽</span>
                        <span>🙆🏽</span>
                        <span>💁🏽</span>
                        <span>🙋🏽</span>
                        <span>🙇🏽</span>
                        <span>🚶🏾</span>
                        <span>🏃🏾</span>
                        <span>💃🏾</span>
                        <span>🚣🏾</span>
                        <span>🛀🏾</span>
                        <span>🏄🏾</span>
                        <span>🏇🏾</span>
                        <span>🏊🏾</span>
                        <span>🚴🏾</span>
                        <span>🚵🏾</span>
                        <span>💆🏾</span>
                        <span>💇🏾</span>
                        <span>👰🏾</span>
                        <span>🙍🏾</span>
                        <span>🙎🏾</span>
                        <span>🙅🏾</span>
                        <span>🙆🏾</span>
                        <span>💁🏾</span>
                        <span>🙋🏾</span>
                        <span>🙇🏾</span>
                    </div>
                    <div class="emoji-list" id="emoji_nature" style="display:none">
                        <span>🐶</span>
                        <span>🐱</span>
                        <span>🐭</span>
                        <span>🐹</span>
                        <span>🐰</span>
                        <span>🐻</span>
                        <span>🐼</span>
                        <span>🐨</span>
                        <span>🐯</span>
                        <span>🐮</span>
                        <span>🐷</span>
                        <span>🐽</span>
                        <span>🐸</span>
                        <span>🐙</span>
                        <span>🐵</span>
                        <span>🙈</span>
                        <span>🙉</span>
                        <span>🙊</span>
                        <span>🐒</span>
                        <span>🐔</span>
                        <span>🐧</span>
                        <span>🐦</span>
                        <span>🐤</span>
                        <span>🐣</span>
                        <span>🐥</span>
                        <span>🐺</span>
                        <span>🐗</span>
                        <span>🐴</span>
                        <span>🐝</span>
                        <span>🐛</span>
                        <span>🐌</span>
                        <span>🐞</span>
                        <span>🐜</span>
                        <span>🐍</span>
                        <span>🐢</span>
                        <span>🐠</span>
                        <span>🐟</span>
                        <span>🐡</span>
                        <span>🐬</span>
                        <span>🐳</span>
                        <span>🐋</span>
                        <span>🐊</span>
                        <span>🐆</span>
                        <span>🐅</span>
                        <span>🐃</span>
                        <span>🐂</span>
                        <span>🐄</span>
                        <span>🐪</span>
                        <span>🐫</span>
                        <span>🐘</span>
                        <span>🐐</span>
                        <span>🐏</span>
                        <span>🐑</span>
                        <span>🐎</span>
                        <span>🐖</span>
                        <span>🐀</span>
                        <span>🐁</span>
                        <span>🐓</span>
                        <span>🐕</span>
                        <span>🐩</span>
                        <span>🐈</span>
                        <span>🐇</span>
                        <span>🐾</span>
                        <span>🐉</span>
                        <span>🐲</span>
                        <span>🌵</span>
                        <span>🎄</span>
                        <span>🌲</span>
                        <span>🌳</span>
                        <span>🌴</span>
                        <span>🌱</span>
                        <span>🌿</span>
                        <span>☘</span>
                        <span>🍀</span>
                        <span>🎍</span>
                        <span>🎋</span>
                        <span>🍃</span>
                        <span>🍂</span>
                        <span>🍁</span>
                        <span>🌾</span>
                        <span>🌺</span>
                        <span>🌻</span>
                        <span>🌹</span>
                        <span>🌷</span>
                        <span>🌼</span>
                        <span>🌸</span>
                        <span>💐</span>
                        <span>🍄</span>
                        <span>🌰</span>
                        <span>🎃</span>
                        <span>🐚</span>
                        <span>🌎</span>
                        <span>🌍</span>
                        <span>🌏</span>
                        <span>🌕</span>
                        <span>🌖</span>
                        <span>🌗</span>
                        <span>🌘</span>
                        <span>🌑</span>
                        <span>🌒</span>
                        <span>🌓</span>
                        <span>🌔</span>
                        <span>🌚</span>
                        <span>🌝</span>
                        <span>🌛</span>
                        <span>🌜</span>
                        <span>🌞</span>
                        <span>🌙</span>
                        <span>⭐️</span>
                        <span>🌟</span>
                        <span>💫</span>
                        <span>✨</span>
                        <span>☀️</span>
                        <span>⛅️</span>
                        <span>☁️</span>
                        <span>⚡️</span>
                        <span>🔥</span>
                        <span>💥</span>
                        <span>❄️</span>
                        <span>🔥</span>
                        <span>💥</span>
                        <span>❄️</span>
                        <span>⛄️</span>
                        <span>💨</span>
                        <span>☔️</span>
                        <span>💧</span>
                        <span>💦</span>
                        <span>🌊</span>
                    </div>
                    <div class="emoji-list" id="emoji_fruits" style="display:none">
                        <span>🍏</span>
                        <span>🍎</span>
                        <span>🍐</span>
                        <span>🍊</span>
                        <span>🍋</span>
                        <span>🍌</span>
                        <span>🍉</span>
                        <span>🍇</span>
                        <span>🍓</span>
                        <span>🍈</span>
                        <span>🍒</span>
                        <span>🍑</span>
                        <span>🍍</span>
                        <span>🍅</span>
                        <span>🍆</span>
                        <span>🌽</span>
                        <span>🍠</span>
                        <span>🍯</span>
                        <span>🍞</span>
                        <span>🍗</span>
                        <span>🍖</span>
                        <span>🍤</span>
                        <span>🍳</span>
                        <span>🍔</span>
                        <span>🍟</span>
                        <span>🍕</span>
                        <span>🍝</span>
                        <span>🍜</span>
                        <span>🍲</span>
                        <span>🍥</span>
                        <span>🍣</span>
                        <span>🍱</span>
                        <span>🍛</span>
                        <span>🍙</span>
                        <span>🍚</span>
                        <span>🍘</span>
                        <span>🍢</span>
                        <span>🍡</span>
                        <span>🍧</span>
                        <span>🍨</span>
                        <span>🍦</span>
                        <span>🍰</span>
                        <span>🎂</span>
                        <span>🍮</span>
                        <span>🍬</span>
                        <span>🍭</span>
                        <span>🍫</span>
                        <span>🍩</span>
                        <span>🍪</span>
                        <span>🍺</span>
                        <span>🍻</span>
                        <span>🍷</span>
                        <span>🍸</span>
                        <span>🍹</span>
                        <span>🍶</span>
                        <span>🍵</span>
                        <span>☕️</span>
                        <span>🍼</span>
                        <span>🍴</span>
                    </div>
                    <div class="emoji-list" id="emoji_travel" style="display:none">
                        <span>🚗</span>
                        <span>🚕</span>
                        <span>🚙</span>
                        <span>🚌</span>
                        <span>🚎</span>
                        <span>🚓</span>
                        <span>🚑</span>
                        <span>🚒</span>
                        <span>🚐</span>
                        <span>🚚</span>
                        <span>🚛</span>
                        <span>🚜</span>
                        <span>🚲</span>
                        <span>🚨</span>
                        <span>🚔</span>
                        <span>🚍</span>
                        <span>🚘</span>
                        <span>🚖</span>
                        <span>🚡</span>
                        <span>🚠</span>
                        <span>🚟</span>
                        <span>🚃</span>
                        <span>🚋</span>
                        <span>🚝</span>
                        <span>🚄</span>
                        <span>🚅</span>
                        <span>🚈</span>
                        <span>🚞</span>
                        <span>🚂</span>
                        <span>🚆</span>
                        <span>🚇</span>
                        <span>🚊</span>
                        <span>🚉</span>
                        <span>🚁</span>
                        <span>✈️</span>
                        <span>⛵️</span>
                        <span>🚤</span>
                        <span>🚀</span>
                        <span>💺</span>
                        <span>⚓️</span>
                        <span>🚧</span>
                        <span>⛽️</span>
                        <span>🚏</span>
                        <span>🚦</span>
                        <span>🚥</span>
                        <span>🏁</span>
                        <span>🚢</span>
                        <span>🎡</span>
                        <span>🎢</span>
                        <span>🎠</span>
                        <span>🌁</span>
                        <span>🗼</span>
                        <span>🏭</span>
                        <span>⛲️</span>
                        <span>🎑</span>
                        <span>🗻</span>
                        <span>🌋</span>
                        <span>🗾</span>
                        <span>⛺️</span>
                        <span>🌅</span>
                        <span>🌄</span>
                        <span>🌇</span>
                        <span>🌆</span>
                        <span>🌃</span>
                        <span>🌉</span>
                        <span>🌌</span>
                        <span>🌠</span>
                        <span>🎇</span>
                        <span>🎆</span>
                        <span>🌈</span>
                        <span>🏰</span>
                        <span>🏯</span>
                        <span>🗽</span>
                        <span>🏠</span>
                        <span>🏡</span>
                        <span>🏢</span>
                        <span>🏬</span>
                        <span>🏣</span>
                        <span>🏤</span>
                        <span>🏥</span>
                        <span>🏦</span>
                        <span>🏨</span>
                        <span>🏪</span>
                        <span>🏫</span>
                        <span>🏩</span>
                        <span>💒</span>
                        <span>⛪️</span>
                    </div>
                    <div class="emoji-list" id="object_emojis" style="display:none;">
                        <span>❤️</span>
                        <span>💛</span>
                        <span>💙</span>
                        <span>💜</span>
                        <span>💔</span>
                        <span>💕</span>
                        <span>💞</span>
                        <span>💓</span>
                        <span>💗</span>
                        <span>💖</span>
                        <span>💘</span>
                        <span>💝</span>
                        <span>💟</span>
                        <span>🔯</span>
                        <span>⛎</span>
                        <span>♈️</span>
                        <span>♉️</span>
                        <span>♊️</span>
                        <span>♋️</span>
                        <span>♌️</span>
                        <span>♍️</span>
                        <span>♎️</span>
                        <span>♏️</span>
                        <span>♐️</span>
                        <span>♑️</span>
                        <span>♒️</span>
                        <span>♓️</span>
                        <span>🆔</span>
                        <span>🈳</span>
                        <span>🈹</span>
                        <span>📴</span>
                        <span>📳</span>
                        <span>🈶</span>
                        <span>🈚️</span>
                        <span>🈸</span>
                        <span>🈺</span>
                        <span>🈷️</span>
                        <span>✴️</span>
                        <span>🆚</span>
                        <span>🉑</span>
                        <span>💮</span>
                        <span>🉐</span>
                        <span>㊙️</span>
                        <span>㊗️</span>
                        <span>🈴</span>
                        <span>🈵</span>
                        <span>🈲</span>
                        <span>🅰️</span>
                        <span>🅱️</span>
                        <span>🆎</span>
                        <span>🆑</span>
                        <span>🅾️</span>
                        <span>🆘</span>
                        <span>⛔️</span>
                        <span>📛</span>
                        <span>🚫</span>
                        <span>❌</span>
                        <span>⭕️</span>
                        <span>💢</span>
                        <span>♨️</span>
                        <span>🚷</span>
                        <span>🚯</span>
                        <span>🚳</span>
                        <span>🚱</span>
                        <span>🔞</span>
                        <span>📵</span>
                        <span>❗️</span>
                        <span>❕</span>
                        <span>❓</span>
                        <span>❔</span>
                        <span>‼️</span>
                        <span>⁉️</span>
                        <span>💯</span>
                        <span>🔅</span>
                        <span>🔆</span>
                        <span>🔱</span>
                        <span>⚜</span>
                        <span>〽️</span>
                        <span>⚠️</span>
                        <span>🚸</span>
                        <span>🔰</span>
                        <span>♻️</span>
                        <span>🈯️</span>
                        <span>💹</span>
                        <span>❇️</span>
                        <span>✳️</span>
                        <span>❎</span>
                        <span>✅</span>
                        <span>💠</span>
                        <span>🌀</span>
                        <span>➿</span>
                        <span>🌐</span>
                        <span>Ⓜ️</span>
                        <span>🏧</span>
                        <span>🈂️</span>
                        <span>🛂</span>
                        <span>🛃</span>
                        <span>🛄</span>
                        <span>🛅</span>
                        <span>♿️</span>
                        <span>🚭</span>
                        <span>🚾</span>
                        <span>🅿️</span>
                        <span>🚰</span>
                        <span>🚹</span>
                        <span>🚺</span>
                        <span>🚼</span>
                        <span>🚻</span>
                        <span>🚮</span>
                        <span>🎦</span>
                        <span>📶</span>
                        <span>🈁</span>
                        <span>🆖</span>
                        <span>🆗</span>
                        <span>🆙</span>
                        <span>🆒</span>
                        <span>🆕</span>
                        <span>🆓</span>
                        <span>🔟</span>
                        <span>🔢</span>
                        <span>▶️</span>
                        <span>⏩</span>
                        <span>⏪</span>
                        <span>🔀</span>
                        <span>🔁</span>
                        <span>🔂</span>
                        <span>◀️</span>
                        <span>🔼</span>
                        <span>🔽</span>
                        <span>⏫</span>
                        <span>⏬</span>
                        <span>➡️</span>
                        <span>⬅️</span>
                        <span>⬆️</span>
                        <span>⬇️</span>
                        <span>↗️</span>
                        <span>↘️</span>
                        <span>↙️</span>
                        <span>↖️</span>
                        <span>↕️</span>
                        <span>↔️</span>
                        <span>🔄</span>
                        <span>↪️</span>
                        <span>↩️</span>
                        <span>⤴️</span>
                        <span>⤵️</span>
                        <span>ℹ️</span>
                        <span>🔤</span>
                        <span>🔡</span>
                        <span>🔠</span>
                        <span>🔣</span>
                        <span>🎵</span>
                        <span>🎶</span>
                        <span>〰️</span>
                        <span>➰</span>
                        <span>✔️</span>
                        <span>🔃</span>
                        <span>➕</span>
                        <span>➖</span>
                        <span>➗</span>
                        <span>✖️</span>
                        <span>💲</span>
                        <span>💱</span>
                        <span>©️</span>
                        <span>®️</span>
                        <span>™️</span>
                        <span>🔚</span>
                        <span>🔙</span>
                        <span>🔛</span>
                        <span>🔝</span>
                        <span>🔜</span>
                        <span>☑️</span>
                        <span>🔘</span>
                        <span>⚪️</span>
                        <span>⚫️</span>
                        <span>🔴</span>
                        <span>🔵</span>
                        <span>🔸</span>
                        <span>🔹</span>
                        <span>🔶</span>
                        <span>🔷</span>
                        <span>🔺</span>
                        <span>▪️</span>
                        <span>▫️</span>
                        <span>⬛️</span>
                        <span>⬜️</span>
                        <span>🔻</span>
                        <span>◼️</span>
                        <span>◻️</span>
                        <span>◾️</span>
                        <span>◽️</span>
                        <span>🔲</span>
                        <span>🔳</span>
                        <span>🔈</span>
                        <span>🔉</span>
                        <span>🔊</span>
                        <span>🔇</span>
                        <span>📣</span>
                        <span>📢</span>
                        <span>🔔</span>
                        <span>🔕</span>
                        <span>🃏</span>
                        <span>🀄️</span>
                        <span>♠️</span>
                        <span>♣️</span>
                        <span>♥️</span>
                        <span>♦️</span>
                        <span>🎴</span>
                        <span>🕐</span>
                        <span>🕑</span>
                        <span>🕒</span>
                        <span>🕓</span>
                        <span>🕔</span>
                        <span>🕕</span>
                        <span>🕖</span>
                        <span>🕗</span>
                        <span>🕘</span>
                        <span>🕙</span>
                        <span>🕚</span>
                        <span>🕛</span>
                        <span>🕜</span>
                        <span>🕝</span>
                        <span>🕞</span>
                        <span>🕟</span>
                        <span>🕠</span>
                        <span>🕡</span>
                        <span>🕢</span>
                        <span>🕣</span>
                        <span>🕤</span>
                        <span>🕥</span>
                        <span>🕦</span>
                        <span>🕧</span>
                    </div>

                </div>
        </div>
    </div>
</section>

<script src="js/main.js"></script>
